### ISSUE TITLE
Dynamic tag name / prop name

### ISSUE THREAD

**Issue by dy** [developit/htm#109]
Calculated tag name or props:

```js
html`<page-${page} />`
html`<div#${id}.${className} />`
html`<div class="${'a'} ${'b'}"/>`
```
aren't possible with `htm` now.

That's a feature-request.

**Comment by jviide** [comment]
This has been implemented & merged in https://github.com/developit/htm/pull/93.

**Comment by jviide** [comment]
Nope, sorry, I was thinking of attribute values!

**Comment by jviide** [comment]
@dy Currently there is no special syntax for this, but ``` html`<${"page-" + page} />` ``` should work.

**Comment by developit** [comment]
Hiya - I really don't think HTM should be extended with hyperscript-style syntax. For that, use hyperscript.

Calculated tag names are both confusing and of extremely limited use - they can't represent components because the concatenated value is always a String, so they are limited to representing two pieces of the same string. For that, @jviide's example is sufficient and easy to understand.
