### ISSUE TITLE
htm/mini tradeoff

### ISSUE THREAD

**Issue by osdevisnot** [developit/htm#121]
Maybe I am missing the point of `htm/mini`, but I can't justify the tradeoff here. It saves 150 bytes, but adds 10 conditionals, which kind of make the code little more verbose. 

Do we have a future plan to expand the main version to consider keeping mini version? I am guessing we might see more adoption of mini version if we add more features to main version.

**Comment by mindplay-dk** [comment]
I don't know why something this small even needs a "mini" version? :man_shrugging:

**Comment by developit** [comment]
We've considered dropping the `/mini` build, since currently the main thing it does is remove caching. Now that we don't include a ponyfill for `Map`, the size impact of the "full" HTM build with caching enabled is less dramatic.

One thing to note though: it's easy to make things seem justifiable when using absolute file sizes, however this is dangerous when the point of comparison is already extremely small. Yes, mini is only 163b smaller than the full version when gzipped - but that's still 25%.

In general, the way we've solved these types of tradeoffs in HTM and Preact is by working magic to reduce the size of the full version to the point where the tradeoff is basically gone. I do think there's some potential for that here, since currently a bunch of the size difference comes from `build()` being intentionally not inlined by Terser.

> **Update:** I just played around and was able to bring the full version down 5%, from 644b to 613b.

**Comment by Grafikart** [comment]
I'm currently using mini cause the "normal" version seems to have a cache that creates problem if your h() function render a DomElement. Indeed htm will reuse the last return and the same dom reference will be used.

```js
const items = [1, 2, 3]
    return html`<div>
    ${items.map(b => html`<button class="btn-gradient"><span>Hello</span></button>`)}
    </div>`
```

Since nothing change for the button, the method h() would be called once :( 
If mini disappear maybe we should have a way to completely disable cache (maybe in the bind function)

**Comment by zaceno** [comment]
+1 for what @Grafikart said. The caching causes bugs when using htm with hyperapp. So I'm currently using the mini version not for its small size but because it skips caching.

If we get rid of the minified version, I would at least like there to be an option to disable caching. Perhaps via the bind command? I e:

```
const html = htm.bind(h, {caching: false}) //by default it is true
```

**Comment by heyheyhello** [comment]
@Grafikart I'd recommend explicitly cloning the nodes rather than disabling cache:

```js
const btn = html`<button class="btn-gradient"><span>Hello</span></button>`
  return html`
  <div>
    ${items.map(b => btn.cloneNode(true))}
  </div>`
```

While we all appreciate htm as a parser, it's actually very expensive. The caching step can save lots of work. Try putting yourself in htm's place and imagine parsing your `<button...` call through the 292 lines of code (!) to generate your DOM node, each time. That's a lot of wasted work, and it would be a lot more efficient to leverage the browser to clone nodes for you - promise it'll be faster than having htm do all the work again and again.

https://codesandbox.io/s/happy-pare-hgqkc?file=/src/index.js

**Comment by developit** [comment]
Excellent answer @heyheyhello.
