### ISSUE TITLE
"Using incorrect casing" error from React

### ISSUE THREAD

**Issue by thebordella** [developit/htm#126]
I am new to React/HTM so maybe I am doing something wrong here. I am trying to get a simple test page working. The code is here:

[https://codepen.io/beagle72/pen/dyyyaMa](url)

The ReactDOM.render function produces an error about the dynamically inserted &lt;MyWidget /&gt;tag:

react-dom.js:496 Warning: &lt;MyWidget /&gt; is using incorrect casing. Use PascalCase for React components, or lowercase for HTML elements.

Also note that if I remove the render() statement and add a literal &lt;MyWidget /&gt; to the HTML, the component class for it never executes. I have also tried making the component class into a React function, but it still never executes.

If I move the whole &lt;script /&gt; block into &lt;head /&gt; nothing changes, same problems.

I don't quite understand how to make the HTM syntax work here. Thank you!

**Comment by pcr910303** [comment]
@thebordella It should be like this:
```js
html`<${MyWidget} />`
```
instead of this:
```js
html`<MyWidget />`
```

If your unfamiliar with React (as I would not expect anyone to put a component into HTML), I would take a more usual approach using Babel & Webpack or just CRA, instead of running into multiple issues with both React & htm, since this setup isn't really popular.

**Comment by thebordella** [comment]
Yes, that worked! I understand now. Thank you for the advice.
