### ISSUE TITLE
Newline spaces are lost

### ISSUE THREAD

**Issue by dy** [developit/htm#128]
```js
import { render } from 'preact'; 
import { html } from 'htm/preact';

render(html`
a
b
`, document.body);
document.body.textContent // 'a b'

render(html`
${'a'}
${'b'}
`, document.body);
document.body.textContent // 'ab'
```
[sandbox](https://codesandbox.io/s/pensive-mccarthy-rwmo8?fontsize=14)

Is this normal? A bit unexpected trim side-effect.

**Comment by jviide** [comment]
This is expected behavior and mimics JSX. See [this Babel playground example](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBAZiEMC8MA8ATAlgNwHwBQA3gEQCGJAvsSQEZUFoD02-A3AQaJLLWQE4p0rQmQK1GLXHjZA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=7.6.4&externalPlugins=).
