### ISSUE TITLE
Is This project still maintained? 

### ISSUE THREAD

**Issue by jupiter-mic** [developit/htm#138]

**Comment by pcr910303** [comment]
@jupiter-mic Well the last commit is about two months ago, the maintainer is appearing in questions & bug reports... it's really well maintained IMHO.

**Comment by developit** [comment]
This is a project that meets a set of extremely strict goals, which means there is little in the way of maintenance necessary. That means the release frequency is much lower, but please don't mistake this for an indicator that the module is not being maintained. When evaluating whether something is maintained, look at code quality and tests first - a well-tested module with CI in place and good code quality may not need a constant stream of releases to keep up with the ecosystem around it. Then look at usage stats (on the rise), interest (stars on github, discussions), maintainer involvement (see @jviide and I talking about this module on Twitter, between the puns), and proposal PRs (even those unmerged ones!).

In HTM's case, the project does an extremely good job delivering on the goals set out in the readme, and since the JSX spec it follows is locked in time there's not much in the way of foundational work to be done. Despite this, @jviide has a few open PR's that implement features beyond the scope of JSX compatibility, but these require some changes in Preact in order to provide the intended performance benefits. This is all stuff we're going to do, it just takes more time than basic maintenance tasks because of the coordination across projects.
