### ISSUE TITLE
Copyright 2018 Google Inc ???

### ISSUE THREAD

**Issue by xkam** [developit/htm#139]
Just noticed that some source files contain Google copyright notice, for example -

https://github.com/developit/htm/blob/master/src/integrations/preact/index.mjs

No concerns for me, just interested if it is intentional or some copy/paste error?

**Comment by developit** [comment]
Hi @xkam - this is not an error, but it is my fault. It's easier to release projects under an Apache-2 license with copyright assignment to Google than it is for me to go through the whole process of claiming copyright, etc. That being said, I think I may need to review this since normally Apache 2 requires contributors sign a CLA and we don't have the Google CLA bot installed here (I don't think I can install it).

This project was actually originally going to be released over on github.com/googlechromelabs, but I thought it would be a little too confusing since at the time of release it was often being compared lit-html (a Google-branded project).

**Comment by xkam** [comment]
Thank you for the explanation. Great job, BTW!
