### ISSUE TITLE
Support HTML5 void elements

### ISSUE THREAD

**Issue by Siilwyn** [developit/htm#171]
It would be great to be able to write standard HTML5 without needing to close tags like in JSX, which is just another small thing to learn for developers.

E.g: an image tag normally works but doesn't in HTM: `<img src="hi.png>`.

**Comment by dy** [comment]
htm@1.x supported that.

I've experimented with implementation of void elements, as well as optional closing elements [here](https://github.com/spectjs/xhtm/pull/5), and noticed that that reduces original HTM performance for ~20% (it needs to check each tag if that's in _void_ list) and increases bundle size ~108 bytes.

**Comment by Siilwyn** [comment]
@dy ah interesting, I don't care for optional closing elements, is that 20% performance difference only caused by supporting void elements?

Maybe it can be given as an option to support since 108 bytes more is not that much, the performance doesn't matter to me since I plan to use 'babel-plugin-htm'.

**Comment by cztomsik** [comment]
you can use this hack:
```
html = html.replace(/<(area|base|br|col|command|embed|hr|img|input|keygen|link|meta|param|source|track|wbr)([^<>]*?)[^\/]>/gi, '<$1$2/>')
```

**Comment by dy** [comment]
@cztomsik but how would you use it with templates `` h`<img src=${src}>` ``?

**Comment by cztomsik** [comment]
I didn't need that (I'm using htm as temporary html parser so I'm just calling `htm.bind(x)([html])`) but you can:

```
import htm from 'https://unpkg.com/htm?module'

const boundHtm = htm.bind((tag, atts, ...kids) => ({ tag, atts, kids }))
const voidBoundHtm = (strings, ...values) => boundHtm(strings.map(addSlash), ...values)
const addSlash = html => html.replace(/<(area|base|br|col|command|embed|hr|img|input|keygen|link|meta|param|source|track|wbr)([^<>]*?)\/?>/gi, '<$1$2/>')

const hello = 'Hello'
console.log(voidBoundHtm`<br><hr><span>${hello}</span>`)
```

It's ugly but it seems to work (and the regex had one bug)

**Comment by developit** [comment]
FWIW one of the reasons I don't think we're likely to consider this is because there are a lot of other HTML features that are unsupported in HTM. Adding a feature like void elements is net negative for performance, but it increases the likelihood of folks thinking HTM is an HTML parser. This assumption breaks down pretty quickly - attribute names are case-sensitive, whitespace is trimmed, etc.

HTM is also most often used with Virtual DOM libraries, which further diverge from HTML since they tend to adopt HTML's property semantics for "props" rather than the string-only semantics of HTML attributes. We've actually had cases in Preact where folks using HTM have run into issues using namespaced attributes. VDOM doesn't have those, and they're only "supported" in HTM because it's faster and smaller to pass-through namespaces than it would be to prevent their usage.

**Comment by Siilwyn** [comment]
Thank you for the reply @developit, much appreciated. I understand the decision. I might publish a `htm@1` project when I find time. :crossed_fingers: 

Will close, ofc. discussion is still possible.

**Comment by cztomsik** [comment]
> of folks thinking HTM is an HTML parser. 

Of course it's not, I'm using it only temporarily

BTW: @developit do you know about some small (well-formed is enough, speed is not an issue) HTML parsers?

**Comment by dy** [comment]
In case if you need htm-compatible API, have a look at xhtm
https://github.com/spectjs/xhtm
