### ISSUE TITLE
Another item for 'Improvements over JSX'

### ISSUE THREAD

**Issue by jzaefferer** [developit/htm#24]
Unlike JSX, HTM doesn't seem to remove line breaks entirely, and instead collapses them to spaces, just like HTML.

At least based on this limited test: https://glitch.com/edit/#!/furry-wind?path=index.html:3:0 (I don't really know how to share stuff with glitch properly)

I'm not sure how to describe that JSX issue properly; would've sent a PR otherwise.

**Comment by developit** [comment]
I've let this one sit for a bit because we might switch over to using a custom parser in order to make Node support a bit more optimal. Once that decision is made we can figure out whether to add this to the readme.

**Comment by developit** [comment]
I believe this behaviour changed in 2.0 to align with the JSX spec.

As with the HTML->XML transition, it's likely some people would prefer whitespace preservation whereas others would prefer whitespace to be collapsed. Since `htm` is promoted as a JSX alternative I think it's probably best for us to go with what JSX does.

FWIW I would imagine a preprocessing step would work here:

```js
import { html as originalHtml } from 'htm/preact';

const html = (statics, ...exprs) => originalHtml(statics.map(reduceWhitespace), exprs);
const reduceWhitespace = str => str.replace(/[\s\n]*\n[\s\n]*/, ' ');

html`
  <div>
    this
    is
    text
  </div>
`
```
