### ISSUE TITLE
Is it possible to implement hooks 🙄?

### ISSUE THREAD

**Issue by haikyuu** [developit/htm#46]
Thanks for this interesting library :)

Is it possible to implement hooks in some sort?

**Comment by developit** [comment]
Hooks is up to the library being used with HTM. If you mean in HTM/preact that's coming!

**Comment by talentlessguy** [comment]
Please re-open the issue. The following code doesn't work with Preact X and htm:

```js
import htm from 'htm'
import { h, render } from 'preact'
import { useState } from 'preact/hooks'

const html = htm.bind(h)

const App = () => {
  const [count, setCount] = useState(0)

  return html`
  <div>
    <h1>Counter: ${count}</h1>
    <button onClick=${() => setCount(count+1)}>+1</button>
  </div>
  `
}

render(html`<${App} />`, document.body)
```

And it gets weirder because it works on [CodeSandbox](https://codesandbox.io/s/modest-wozniak-cs7sw) but not on local setup.

Here is the error message on local setup (in Firefox 68):

```
TypeError: u is null
    render.js:17:5
    T render.js:17
    parcelRequire<["index.js"]< index.js:18
    Preact 3
```

And package.json:

```json
{
  "name": "preact-htm-parcel",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "htm": "^2.1.1",
    "preact": "10.0.0-beta.2"
  },
  "devDependencies": {
    "parcel-bundler": "^1.12.3"
  },
  "scripts": {
    "start": "parcel index.html -p 80"
  }
}
```

And html file:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <script src="index.js"></script>
</head>
<body>
</body>
</html>
```

**Comment by jviide** [comment]
@talentlessguy Instead of hooks could the issue be that caused by `<script src="index.js"></script>` being inside the `<head>` element? `document.body` is probably `null` when index.js is run, because at that point the HTML parser hasn't yet encountered the `<body>` tag. If this is the case then you can solve the issue by moving the script tag inside the body, like so:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  <script src="index.js"></script>
</body>
</html>
```

**Comment by talentlessguy** [comment]
@jviide uh sorry for my stupidity. I thought that `document.body ` is accessible before its load but I was wrong. No need to re-open

**Comment by jviide** [comment]
@talentlessguy Nah, it's not stupid at all. I'd wager most web devs (myself included) have been bitten by some variation of this along the way 🙂

**Comment by crazy4groovy** [comment]
Is `hooks` available via the standalone?

eg. `import { html, useState } from 'https://unpkg.com/htm/preact/standalone.mjs';`

Or some other similar way?

eg. `import { useState } from 'https://unpkg.com/htm/preact/hooks.mjs';`

(Would like to use hooks via script modules)
