### ISSUE TITLE
Cannon read property apply of undefined

### ISSUE THREAD

**Issue by liron-navon** [developit/htm#80]
basic string interpolation fails for some reason.

<img width="926" alt="Screen Shot 2019-04-03 at 12 55 10" src="https://user-images.githubusercontent.com/18119833/55473784-ca4c3180-560f-11e9-9a2d-26ab0017fc41.png">

<img width="1580" alt="Screen Shot 2019-04-03 at 12 58 58" src="https://user-images.githubusercontent.com/18119833/55473998-5e1dfd80-5610-11e9-8695-16d77278bbd4.png">

**Comment by Kanaye** [comment]
Hi @liron-navon.

I can't reproduce this error with preact and htm: [example](https://codesandbox.io/s/zqw23kxlo4).
Can you post a link to your full example code running on [codesandbox](https://codesandbox.io) or something similar?

**Comment by jviide** [comment]
You probably need to do `const html = htm.bind(h)` for some `h` first (and use `html` for your templates after that instead of `htm` directly). See the [Usage](https://github.com/developit/htm#usage) part of the README. The [Installation](https://github.com/developit/htm#installation) section also has examples that are specific to React and Preact.

**Comment by developit** [comment]
Yup, this error happens when you forget to bind. `htm` isn't a parser, its a parser factory.
